version: "3.7"
services:
  web:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - .:/var/www
      - .docker/web/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    build: .docker/php
    volumes:
      - .:/var/www
      - .docker/php/php.ini:/usr/local/etc/php/conf.d/zzz-php.ini
    links:
      - db
  db:
    image: postgres:12
    env_file: .docker/db/.env
    ports:
      - 54321:5432
    volumes:
      - .postgres-data:/var/lib/postgresql/data
